Repository is-a-good-dev/register, pull requests merged in 2023-02, with the labels that each got.

#377 add my json
  sub-logs/sharad-rajyaguru.json
Labels: Helpers: Do not Merge, Awaiting Response, Do Not Merge

#376 Register my domain
  sub-logs/shoaib-shaikhh.json
Labels: Helpers: Do not Merge, Do Not Merge

#375 Add json file
  sub-logs/akta-chavda.json
Labels: Helpers: Do not Merge, Do Not Merge

#374 Create nitesh-rathod json file
  sub-logs/nitesh-rathod.json
Labels: Helpers: Do not Merge, Do Not Merge

#373 Add my domain
  sub-logs/vyas-rahul.json
Labels: Helpers: Do not Merge, Do Not Merge

#372 Add my json
  sub-logs/pathan-imran.json
Labels: Helpers: Do not Merge, Do Not Merge

#371 Create my domain
  sub-logs/nayan-gorasiya.json
Labels: Helpers: Do not Merge, Do Not Merge

#370 my json
  sub-logs/keyurnimavat.json
Labels: Helpers: Do not Merge, Do Not Merge

#369 Create json
  sub-logs/hiren-brahmbhatt.json
Labels: Helpers: Do not Merge, Do Not Merge

#368 Add nikunj domain
  sub-logs/mandaninikunj.json
Labels: Helpers: Do not Merge, Do Not Merge

#367 Register my domain
  sub-logs/kaushik-bhadarka.json
Labels: Helpers: Do not Merge, Do Not Merge

#366 Add my json
  sub-logs/jagdish-mer.json
Labels: Helpers: Do not Merge, Do Not Merge

#365 Add my json file
  sub-logs/jagdish-der.json
Labels: Helpers: Do not Merge, Do Not Merge

#364 Add my json
  sub-logs/jay-bhalodiya.json
Labels: Helpers: Do not Merge, Do Not Merge

#363 Add my json
  sub-logs/patel-hetal.json
Labels: Helpers: Do not Merge, Do Not Merge

#362 Register my domain
  sub-logs/grishma-chhayani.json
Labels: Helpers: Do not Merge, Do Not Merge

#361 sanjay domain
  sub-logs/sanjay-suryavanshi.json
Labels: Helpers: Do not Merge, Do Not Merge

#360 sanjeet domain
  sub-logs/verma-sanjeet.json
Labels: Helpers: Do not Merge, Do Not Merge

#359 add palak domain
  sub-logs/lakhani-palak.json
Labels: Helpers: Do not Merge, Do Not Merge

#358 Create json
  sub-logs/prajapati-divya.json
Labels: Helpers: Do not Merge, Do Not Merge

#357 riddhi-domain
  sub-logs/pandya-riddhi.json
Labels: Helpers: Do not Merge, Do Not Merge

#356 Register shakeel domain
  sub-logs/shakeel-ahamad.json
Labels: Helpers: Do not Merge, Do Not Merge

#355 Add my json file
  sub-logs/ajay-charotariya.json
Labels: Helpers: Do not Merge, Do Not Merge

#354 viren json
  sub-logs/viren-trivedi.json
Labels: Helpers: Do not Merge, Do Not Merge

#353 Add my domain
  sub-logs/yash-poojara.json
Labels: Helpers: Do not Merge, Do Not Merge

#352 Create my json
  sub-logs/ajit-thakor.json
Labels: Helpers: Do not Merge, Do Not Merge

#351 add my custom domain
  sub-logs/viral-gadhiya.json
Labels: Helpers: Do not Merge, Do Not Merge

#350 meet domain
  sub-logs/dudani-meet.json
Labels: Helpers: Do not Merge, Do Not Merge

#349 Add my domain
  sub-logs/priti-shide.json
Labels: Helpers: Do not Merge, Do Not Merge

#348 Register my json
  sub-logs/mihir-patel-agc.json
Labels: Helpers: Do not Merge, Validated

#342 Delete william.json
  sub-logs/william.json
Labels: Helpers: Do not Merge

#340 Delete as I don't need this as of now.
  sub-logs/dibster.json
Labels: Helpers: Do not Merge

#400 Register william.is-a-good.dev
  sub-logs/william.json
Labels: Validated
