Repository is-a-good-dev/register, pull requests merged in 2023-01, with the labels that each got.

#311 Create snox.json
  sub-logs/snox.json
Labels: Awaiting Response

#309 Clean up CI code
  utils/checkRecords.js
  utils/utils.js
Labels: Validated

#314 update hyro to vercel
  sub-logs/hyro.json
Labels: Validated

#316 Create ryan.json
  sub-logs/ryan.json
Labels: Validated

#317 unknown
  sub-logs/unknown.json
Labels: Helpers: Do not Merge, Awaiting Response

#318 Create william.json
  sub-logs/william.json
Labels: Validated

#329 Create pywhatkit.pywhatkit-team.json
  sub-logs/pywhatkit-team.json
Labels: Validated

#343 Create ricky.json
  sub-logs/ricky.json
Labels: Format Issue
