Repository is-a-good-dev/register, pull requests merged in 2024-12, with the labels that each got.

#756 Create john.json
  domains/john.json
Labels: Helpers: Do not Merge, Awaiting Response

#758 Add TortillaGames
  domains/tortilla.json
Labels: Helpers: Do not Merge, Awaiting Response

#764 Add subdomain configuration for parth.is-a-good.dev
  domains/parth.json
Labels: Invalid

#769 Update nolimanom.json
  domains/nolimanom.json
Labels: Awaiting Response, Do Not Merge
