Repository is-a-good-dev/register, pull requests merged in 2024-11, with the labels that each got.

#731 Register nolimanom.is-a-good.dev
  sub-logs/nolimanom.json
Labels: Awaiting Response, Do Not Merge

#723 feat(ci): support NS records
  dnsconfig.js
  domains/william.json
Labels: Enhancement, Validated

#745 Delete domains/william.json
  domains/william.json
Labels: Validated
