Repository is-a-good-dev/register, pull requests merged in 2025-04, with the labels that each got.

#855 Create whothree.json
  domains/whothree.json
Labels: Record Issue

#862 Create mhzsam.json
  domains/mhzsam.json
Labels: Record Issue, Awaiting Response, Do Not Merge

#869 Create princevora.json
  domains/princevora.json
Labels: Awaiting Response, Do Not Merge
