Repository is-a-good-dev/register, pull requests merged in 2025-08, with the labels that each got.

#924 Update imbazim.json to fix issues
  domains/imbazim.json
Labels: Stale

#923 Created alpheaus.json
  domains/alpheaus.json
Labels: Stale

#927 Create milan.json
  domains/milan.json
Labels: Invalid

#931 Update repository and owner information in zaid.json
  domains/zaid.json
Labels: Record Issue
